import { useEffect, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { generateVideo } from '../services/aiService.js'
import '../styles/results.css'

export default function VideoAdPage() {
  const navigate  = useNavigate()
  const videoRef  = useRef(null)
  const [isPlaying, setIsPlaying] = useState(false)
  const [isRegen, setIsRegen]     = useState(false)
  const [error, setError]         = useState('')

  const stored   = (() => { try { return JSON.parse(sessionStorage.getItem('videoAdData') || '') } catch { return null } })()
  const videoUrl = stored?.video_url || null
  const script   = stored?.script    || ''
  const brand    = stored?.brandData || {}

  useEffect(() => {
    if (!stored) navigate('/')
  }, [])

  function togglePlay() {
    const v = videoRef.current
    if (!v) return
    if (v.paused) { v.play(); setIsPlaying(true) }
    else          { v.pause(); setIsPlaying(false) }
  }

  function handleDownload() {
    if (!videoUrl) return
    const a = Object.assign(document.createElement('a'), {
      href: videoUrl,
      download: `${brand.company_name || 'ad'}_video_ad.mp4`,
      target: '_blank'
    })
    document.body.appendChild(a); a.click(); document.body.removeChild(a)
  }

  function downloadScript() {
    const txt = `VIDEO AD SCRIPT — ${brand.company_name}\n${'='.repeat(50)}\n\n${script}\n\nGenerated by AdStudio AI`
    const a = Object.assign(document.createElement('a'), {
      href: URL.createObjectURL(new Blob([txt], { type: 'text/plain' })),
      download: `${brand.company_name || 'ad'}_script.txt`
    })
    document.body.appendChild(a); a.click(); document.body.removeChild(a)
  }

  async function handleRegenerate() {
    setIsRegen(true)
    setError('')
    try {
      const prompt = brand.video_concept || `A professional advertisement video for ${brand.company_name}.`
      const newVideoUrl = await generateVideo(prompt, brand)
      sessionStorage.setItem('videoAdData', JSON.stringify({ ...stored, video_url: newVideoUrl }))
      window.location.reload()
    } catch (e) {
      setError(e.message || 'Regeneration failed')
    } finally {
      setIsRegen(false)
    }
  }

  if (!stored) return null

  return (
    <div className="result-page">
      {/* Header */}
      <header className="result-header">
        <div className="lp-logo" style={{ cursor:'pointer' }} onClick={() => navigate('/')}>
          <span className="lp-logo-star">✦</span>
          AdStudio <span className="lp-logo-ai">AI</span>
        </div>
        <div className="result-header-center">
          <span className="result-badge">🎬 Video Ad</span>
          <span className="result-company">{brand.company_name}</span>
        </div>
        <button className="btn-ghost" onClick={() => navigate('/')}>← Make Another</button>
      </header>

      <div className="result-body">
        {/* ── Left: Video Player ── */}
        <div className="video-panel">
          <div className="video-wrapper">
            {videoUrl ? (
              <>
                <video
                  ref={videoRef}
                  src={videoUrl}
                  className="video-player"
                  onEnded={() => setIsPlaying(false)}
                  onPlay={() => setIsPlaying(true)}
                  onPause={() => setIsPlaying(false)}
                  preload="auto"
                  playsInline
                />
                <button className="video-play-btn" onClick={togglePlay}>
                  {isPlaying
                    ? <svg viewBox="0 0 24 24" fill="white" width="36" height="36"><rect x="6" y="4" width="4" height="16"/><rect x="14" y="4" width="4" height="16"/></svg>
                    : <svg viewBox="0 0 24 24" fill="white" width="36" height="36"><polygon points="5 3 19 12 5 21 5 3"/></svg>
                  }
                </button>
                <div className="video-brand-badge" style={{ borderLeft: `3px solid ${brand.primary_color}` }}>
                  {brand.company_name}
                </div>
              </>
            ) : (
              <div className="video-error-placeholder">
                <span style={{ fontSize:48 }}>⚠️</span>
                <p>Video generation failed or is still processing.</p>
                <button className="btn-primary" onClick={handleRegenerate} disabled={isRegen}>
                  {isRegen ? 'Generating…' : 'Try Again'}
                </button>
              </div>
            )}
          </div>

          {/* Action buttons */}
          <div className="video-actions">
            <button className="btn-primary" onClick={handleDownload} disabled={!videoUrl}>
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" width="16" height="16">
                <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
                <polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/>
              </svg>
              Download MP4
            </button>
            <button className="btn-secondary" onClick={downloadScript}>
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" width="14" height="14">
                <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
                <polyline points="14 2 14 8 20 8"/>
              </svg>
              Download Script
            </button>
            <button className="btn-ghost" onClick={handleRegenerate} disabled={isRegen}>
              {isRegen ? 'Generating…' : '↺ Regenerate'}
            </button>
          </div>
        </div>

        {/* ── Right: Script + Info ── */}
        <div className="result-side-panel">
          {/* Brand info */}
          <div className="result-brand-card">
            <div className="rbc-row">
              <div className="rbc-dot" style={{ background: brand.primary_color }} />
              <div>
                <div className="rbc-name">{brand.company_name}</div>
                <div className="rbc-industry">{brand.industry}</div>
              </div>
            </div>
            <p className="rbc-tagline">"{brand.tagline}"</p>
          </div>

          {/* Script */}
          <div className="script-section">
            <div className="script-header">
              <h3>Voiceover Script</h3>
              <span className="script-badge">{script ? script.trim().split(/\s+/).length : 0} words</span>
            </div>
            <div className="script-body">
              {script || 'No script generated.'}
            </div>
          </div>

          {/* Key benefits */}
          {brand.key_benefits?.length > 0 && (
            <div className="info-section">
              <h4>Key Benefits</h4>
              <ul className="benefit-list">
                {brand.key_benefits.map(b => <li key={b}>{b}</li>)}
              </ul>
            </div>
          )}
        </div>
      </div>

      {error && <div className="error-toast">{error}</div>}

      {isRegen && (
        <div className="regen-overlay-full">
          <div className="regen-card-inner">
            <div className="spinner large" />
            <p>Generating new video…</p>
            <small>This may take 60–90 seconds</small>
          </div>
        </div>
      )}
    </div>
  )
}
