const CARDS = [
  { icon: '🤖', title: 'AI Brand Analysis', desc: 'Automatically extracts your brand identity — colors, tone, products, audience — from your website content.' },
  { icon: '🖼️', title: 'FLUX AI Image Generation', desc: '6 unique, high-quality ad images generated by FLUX Schnell AI based on your specific brand identity.' },
  { icon: '📝', title: 'Smart Ad Copywriting', desc: 'Gemini 1.5 Flash writes a compelling 30-second voiceover script that perfectly captures your brand voice.' },
  { icon: '🎨', title: 'Full Studio Editor', desc: 'Edit images, bottom banner, end screen, music, voice, and script — all in a beautiful real-time editor.' },
  { icon: '🎵', title: 'Background Music', desc: 'Choose from curated royalty-free music tracks matched to your brand\'s energy and tone.' },
  { icon: '☁️', title: 'Oracle Cloud Ready', desc: 'Built for production deployment on Oracle Cloud Infrastructure (OCI) with enterprise scalability.' },
]

export default function Features() {
  return (
    <section className="features" id="features">
      <div className="section-inner">
        <h2 className="section-title">Everything you need</h2>
        <p className="section-subtitle">Professional ad creation, powered by cutting-edge AI</p>
        <div className="features-grid">
          {CARDS.map(c => (
            <div className="feature-card" key={c.title}>
              <div className="feature-icon">{c.icon}</div>
              <h3>{c.title}</h3>
              <p>{c.desc}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}
